### ISSUE TITLE
nice try

### ISSUE THREAD

**Issue by D3VL-Jack** [cr4zypers0n/Never-Gonna-Give-You-Up#1]
but the scaper is broken lol

**Comment by cr4zypers0n** [comment]
oh no :(

**Comment by cr4zypers0n** [comment]
![rick](https://c.tenor.com/yheo1GGu3FwAAAAd/rick-roll-rick-ashley.gif)

**Comment by cr4zypers0n** [comment]
Closed! The scraper works 😈
